Reprise globale du package

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,34 +1,61 @@
 #!/bin/bash
 
-# Source app helpers
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
 source /usr/share/yunohost/helpers
 
-# Récupère les infos de l'application.
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
 app=$YNH_APP_INSTANCE_NAME
-if [ -z "$app" ]; then
-	app=leed
-fi
 
 final_path=$(ynh_app_setting_get $app final_path)
 domain=$(ynh_app_setting_get $app domain)
+db_name=$(ynh_app_setting_get $app db_name)
+db_pwd=$(ynh_app_setting_get "$app" mysqlpwd)
 
+#=================================================
+# STANDARD BACKUP STEPS
+#=================================================
+# BACKUP OF THE MAIN DIR OF THE APP
+#=================================================
 
-# The parameter $1 is the backup directory location
-# which will be compressed afterward
-backup_dir=$1/apps/$app
-sudo mkdir -p "$backup_dir"
+ynh_backup "$final_path" "sources"
 
-# Backup sources & data
-sudo cp -a $final_path/. $backup_dir/sources
+#=================================================
+# BACKUP OF THE NGINX CONFIGURATION
+#=================================================
 
-# Copy Nginx and YunoHost parameters to make the script "standalone"
-sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
-sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf
+ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"
 
-# Copy dedicated php-fpm process to backup folder
-sudo cp -a /etc/php5/fpm/pool.d/$app.conf $backup_dir/php-fpm.conf
-sudo cp -a /etc/php5/fpm/conf.d/20-$app.ini $backup_dir/php-fpm.ini
+#=================================================
+# BACKUP OF THE PHP-FPM CONFIGURATION
+#=================================================
 
-# Backup db
-root_pwd=$(sudo cat /etc/yunohost/mysql)
-sudo mysqldump -u root -p$root_pwd --no-create-db $app --result-file="$backup_dir/db.sql"
+ynh_backup "/etc/php5/fpm/pool.d/$app.conf" "php-fpm.conf"
+ynh_backup "/etc/php5/fpm/conf.d/20-$app.ini" "php-fpm.ini"
+
+#=================================================
+# BACKUP OF THE SQL BDD
+#=================================================
+
+mysqldump -u "$db_name" -p"$db_pwd" --no-create-db "$db_name" > ./db.sql
+
+#=================================================
+# SPECIFIC BACKUP
+#=================================================
+# BACKUP OF THE CRON FILE
+#=================================================
+ynh_backup "/etc/cron.d/$app" "cron"
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,17 +1,26 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-CLEAN_SETUP () {
-# Nettoyage des résidus d'installation non pris en charge par le script remove.
-# Pas de nettoyage supplémentaire nécessaire ici...
-	echo ""
-}
-TRAP_ON	# Active trap pour arrêter le script si une erreur est détectée.
+source .fonctions
+source /usr/share/yunohost/helpers
 
-# Retrieve arguments
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+ynh_check_error	# Active trap pour arrêter le script si une erreur est détectée.
+
+#=================================================
+# RETRIEVE ARGUMENTS FROM THE MANIFEST
+#=================================================
+
 domain=$YNH_APP_ARG_DOMAIN
-path=$YNH_APP_ARG_PATH
+path_url=$YNH_APP_ARG_PATH
 admin=$YNH_APP_ARG_ADMIN
 user_pwd=$YNH_APP_ARG_PASSWORD
 language=$YNH_APP_ARG_LANGUAGE
@@ -20,49 +29,71 @@ is_public=$YNH_APP_ARG_IS_PUBLIC
 
 app=$YNH_APP_INSTANCE_NAME
 
-# Source app helpers
-source /usr/share/yunohost/helpers
-
-# Vérifie que les variables ne sont pas vides.
-CHECK_VAR "$app" "app name not set"
-
+#=================================================
+# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
+#=================================================
 
 CHECK_USER "$admin"	# Vérifie la validité de l'user admin
-
-CHECK_PATH	# Vérifie et corrige la syntaxe du path.
+path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
 CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.
-
 CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.
 
+#=================================================
+# STORE SETTINGS FROM MANIFEST
+#=================================================
 
-# Enregistre les infos dans la config YunoHost
 ynh_app_setting_set $app admin $admin
 ynh_app_setting_set $app language $language
 ynh_app_setting_set $app domain $domain
 
-GENERATE_DB $app	# Créer une base de données et un utilisateur dédié au nom de l'app.
+#=================================================
+# STANDARD MODIFICATIONS
+#=================================================
+# CREATE A SQL BDD
+#=================================================
 
+db_name=$(ynh_make_valid_dbid $app)
+ynh_app_setting_set $app db_name $db_name
+ynh_mysql_generate_db $db_name $db_name
 
-# Crée le repertoire de destination et stocke son emplacement.
-sudo mkdir "$final_path"
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
 ynh_app_setting_set $app final_path $final_path
+SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path
 
-SETUP_SOURCE "leed.tar.gz"	# Télécharge la source, décompresse et copie dans $final_path
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
 
-# Et copie le fichier de config nginx
+# Copie le fichier de config nginx
 sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
-
-
 # Modifie les variables dans le fichier de configuration nginx
-sudo sed -i "s@__PATH__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
+sudo sed -i "s@__PATHTOCHANGE__@$path_url@g" /etc/nginx/conf.d/$domain.d/$app.conf
 sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf
 sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/$app.conf
 
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
+
+ADD_SYS_USER	# Créer un utilisateur système dédié à l'app
+
+#=================================================
+# PHP-FPM CONFIGURATION
+#=================================================
+
 POOL_FPM	# Créer le fichier de configuration du pool php-fpm et le configure.
 
+#=================================================
+# SPECIFIC SETUP
+#=================================================
+# SETTING UP WITH CURL
+#=================================================
 
 # Set right permissions for curl install
-sudo chown -R www-data: $final_path
+sudo chown -R $app: $final_path
 
 # Rend la page d'install publique pour curl
 ynh_app_setting_set $app unprotected_uris "/"	#L'usage de unprotected_uris a la place de skipped_uris permet de passer le header d'auth http
@@ -72,49 +103,62 @@ sudo yunohost app ssowatconf
 sudo service nginx reload
 
 # Leed installation via curl
-sleep 1	# Évite un mystérieux 404...
-curl -kL -H "Host: $domain" --data "install_changeLngLeed=$language&root=$domain$path&mysqlHost=localhost&mysqlLogin=$db_user&mysqlMdp=$db_pwd&mysqlBase=$db_user&mysqlPrefix=leed_&login=$admin&password=$user_pwd" "https://localhost$path/install.php?installButton" > /dev/null
+YNH_CURL "install_changeLngLeed=$language&root=$domain$path_url&mysqlHost=localhost&mysqlLogin=$db_name&mysqlMdp=$db_pwd&mysqlBase=$db_name&mysqlPrefix=leed_&login=$admin&password=$user_pwd" "/install.php?installButton"
 
-# Activate Leed Market if necessary
+#=================================================
+# ACTIVATE LEED MARKET
+#=================================================
 ynh_app_setting_get $app market "$market"
-if [ "$market" = "Yes" ];
+if [ $market -eq 1 ]
 then
 	sudo rm -R $final_path/plugins
 	sudo git clone https://github.com/ldleman/Leed-market.git "$final_path/plugins"
 fi
 
+#=================================================
+# RETRIEVE SYNCHRONISATION CODE
+#=================================================
 
-# Configure les droits d'accès au fichiers
-# -rw-r--r-- sur les fichiers
-sudo find $final_path -type f | xargs sudo chmod 644
-# drwxr-xr-x sur les dossiers
-sudo find $final_path -type d | xargs sudo chmod 755
-# Les fichiers appartiennent à root
-sudo chown -R root: $final_path
+code_sync=$(mysql -h localhost -u $db_name -p$db_pwd -s $db_name -e 'SELECT value FROM leed_configuration WHERE `key`="synchronisationCode"' | sed -n 1p)
 
-# www-data doit avoir les droits d'écriture dans plugins, cache et updates
-sudo mkdir $final_path/cache
-sudo chown -R www-data $final_path/cache $final_path/plugins $final_path/updates
+#=================================================
+# SETUP CRON FILE FOR SYNCHRONISATION
+#=================================================
 
-
-# Récupération du code de synchronisation
-code_sync=$(mysql -h localhost -u $db_user -p$db_pwd -s $db_user -e 'SELECT value FROM leed_configuration WHERE `key`="synchronisationCode"' | sed -n 1p)
-CHECK_VAR "$code_sync" "code_sync empty"
-
-# Mise en place du cron pour la synchronisation
 sed -i "s@__ADMIN__@$admin@g" ../conf/cron_leed
 sed -i "s@__DOMAIN__@$domain@g" ../conf/cron_leed
-sed -i "s@__PATH__@$path@g" ../conf/cron_leed
+sed -i "s@__PATH__@$path_url@g" ../conf/cron_leed
 sed -i "s@__CODESYNC__@$code_sync@g" ../conf/cron_leed
 sudo cp ../conf/cron_leed /etc/cron.d/$app
 
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# SECURING FILES AND DIRECTORIES
+#=================================================
+
+# Les fichiers appartiennent à root
+sudo chown -R root: $final_path
+# $app doit avoir les droits d'écriture dans plugins, cache et updates
+sudo mkdir $final_path/cache
+sudo chown -R $app $final_path/cache $final_path/plugins $final_path/updates
+
+#=================================================
+# SETUP SSOWAT
+#=================================================
+
 # Make app private if necessary
-ynh_app_setting_get $app is_public "$is_public"
-if [ "$is_public" = "No" ];
+ynh_app_setting_set $app is_public "$is_public"
+if [ $is_public -eq 0 ];
 then
 	# Retire l'autorisation d'accès de la page d'install.
 	ynh_app_setting_delete $app unprotected_uris
 	# Rend la page d'actualisation accessible pour le script cron.
 	ynh_app_setting_get $app skipped_uris "/action.php"
-	sudo yunohost app ssowatconf
 fi
+
+#=================================================
+# RELOAD NGINX
+#=================================================
+
+sudo service nginx reload
diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,37 +1,94 @@
 #!/bin/bash
 
-# Source app helpers
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
 source /usr/share/yunohost/helpers
 
-# Récupère les infos de l'application.
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
 app=$YNH_APP_INSTANCE_NAME
-if [ -z "$app" ]; then
-	app=leed
-fi
-final_path=$(ynh_app_setting_get $app final_path)
+
 domain=$(ynh_app_setting_get $app domain)
+path_url=$(ynh_app_setting_get $app path)
+final_path=$(ynh_app_setting_get $app final_path)
+db_name=$(ynh_app_setting_get $app db_name)
 
-# The parameter $1 is the uncompressed restore directory location
-backup_dir=$1/apps/$app
+#=================================================
+# CHECK IF THE APP CAN BE RESTORED
+#=================================================
 
-# Restore sources & data
-sudo cp -a $backup_dir/sources/. $final_path
+sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
+	|| ynh_die "Path not available: ${domain}${path_url}"
+test ! -d $final_path \
+	|| ynh_die "There is already a directory: $final_path "
 
-# Créer la base de donnée et la restaure
+#=================================================
+# STANDARD RESTORE STEPS
+#=================================================
+# RESTORE OF THE NGINX CONFIGURATION
+#=================================================
+
+conf=/etc/nginx/conf.d/$domain.d/$app.conf
+if [ -f $conf ]; then
+    ynh_die "There is already a nginx conf file at this path: $conf "
+fi
+sudo cp -a ./nginx.conf $conf
+
+#=================================================
+# RESTORE OF THE MAIN DIR OF THE APP
+#=================================================
+
+sudo cp -a ./sources/. $final_path
+
+#=================================================
+# RESTORE OF THE SQL BDD
+#=================================================
+
 db_pwd=$(ynh_app_setting_get $app mysqlpwd)
-db_user=$app
-ynh_mysql_create_db $db_user $db_user $db_pwd
-mysql --debug-check -u $db_user -p$db_pwd $db_user < ${backup_dir}/db.sql
+ynh_mysql_create_db $db_name $db_name $db_pwd
+ynh_mysql_connect_as $db_name $db_pwd $db_name < ./db.sql
 
-# Restore Nginx and YunoHost parameters
-sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
-sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
+#=================================================
+# RECREATE THE DEDICATED USER
+#=================================================
 
-# Copy dedicated php-fpm process from backup folder to the right location
-sudo cp -a $backup_dir/php-fpm.conf /etc/php5/fpm/pool.d/$app.conf
-sudo cp -a $backup_dir/php-fpm.ini /etc/php5/fpm/conf.d/20-$app.ini
-# And restart service
+if ! ynh_system_user_exists "$app"	# Test l'existence de l'utilisateur
+then
+	sudo useradd -d /var/www/$app --system --user-group $app --shell /usr/sbin/nologin || ynh_die "Unable to create $app system account"
+fi
+
+#=================================================
+# RESTORE OF THE PHP-FPM CONFIGURATION
+#=================================================
+
+sudo cp -a ./php-fpm.conf /etc/php5/fpm/pool.d/$app.conf
+sudo cp -a ./php-fpm.ini /etc/php5/fpm/conf.d/20-$app.ini
+
+#=================================================
+# SPECIFIC RESTORE
+#=================================================
+# RESTORE OF THE CRON FILE
+#=================================================
+sudo cp -a "cron" "/etc/cron.d/$app"
+
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# RELOAD NGINX AND PHP-FPM
+#=================================================
+
 sudo service php5-fpm reload
-
-# Restart webserver
 sudo service nginx reload
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,74 +1,142 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-# Récupère les infos de l'application.
-app=$YNH_APP_INSTANCE_NAME
-
-# Source app helpers
+source .fonctions
 source /usr/share/yunohost/helpers
 
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
+
 domain=$(ynh_app_setting_get $app domain)
-path=$(ynh_app_setting_get $app path)
+path_url=$(ynh_app_setting_get $app path)
 admin=$(ynh_app_setting_get $app admin)
 is_public=$(ynh_app_setting_get $app is_public)
 final_path=$(ynh_app_setting_get $app final_path)
 db_pwd=$(ynh_app_setting_get $app mysqlpwd)
+db_name=$(ynh_app_setting_get $app db_name)
+
+#=================================================
+# FIX OLD THINGS
+#=================================================
 
 if [ -z $final_path ]; then	# Si final_path n'est pas renseigné dans app setting
 	final_path=/var/www/$app
 	ynh_app_setting_set $app final_path $final_path
 fi
+if [ -z $db_name ]; then	# Si db_name n'est pas renseigné dans app setting
+	db_name=$(ynh_make_valid_dbid $app)
+	ynh_app_setting_set $app db_name $db_name
+fi
+if [ -z "$is_public" ]; then	# Raté avec get au lieu de set...
+	public_check=$(ynh_app_setting_get $app skipped_uris)
+	if [ -z "$public_check" ]; then	# Si skipped_uris est vide, c'était une install publique.
+		is_public=1
+	else
+		is_public=0
+	fi
+	ynh_app_setting_set $app is_public $is_public
+else
+	if [ "$is_public" = "Yes" ]; then
+		ynh_app_setting_set $app is_public 1	# Fixe is_public en booléen
+		is_public=1
+	elif [ "$is_public" = "No" ]; then
+		ynh_app_setting_set $app is_public 0
+		is_public=0
+	fi
+fi
+market=$(ynh_app_setting_get $app market)
+if [ "$market" = "Yes" ]; then
+	ynh_app_setting_set $app market 1	# Fixe market en booléen
+elif [ "$market" = "No" ]; then
+	ynh_app_setting_set $app market 0
+fi
 
-CHECK_PATH	# Vérifie et corrige la syntaxe du path.
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
 
-SETUP_SOURCE "leed.tar.gz"	# Télécharge la source, décompresse et copie dans $final_path
+BACKUP_BEFORE_UPGRADE	# Backup the current version of the app
+ynh_clean_setup () {
+	BACKUP_FAIL_UPGRADE	# restore it if the upgrade fails
+}
+ynh_check_error	# Active trap pour arrêter le script si une erreur est détectée.
 
-# Et copie le fichier de config nginx
+#=================================================
+# CHECK THE PATH
+#=================================================
+
+path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
+
+#=================================================
+# STANDARD UPGRADE STEPS
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
+SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path
+
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
+
+# Copie le fichier de config nginx
 sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
-
-# Set right permissions
-sudo chown -R www-data: $final_path
-
-# Change variables in Leed configuration
-sudo sed -i "s@__PATH__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
+# Modifie les variables dans le fichier de configuration nginx
+sudo sed -i "s@__PATH__@$path_url@g" /etc/nginx/conf.d/$domain.d/$app.conf
 sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf
 sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/$app.conf
 
-# Créer le fichier de configuration du pool php-fpm et le configure.
-sed -i "s@__NAMETOCHANGE__@$app@g" ../conf/php-fpm.conf
-sed -i "s@__FINALPATH__@$final_path@g" ../conf/php-fpm.conf
-finalphpconf=/etc/php5/fpm/pool.d/$app.conf
-sudo cp ../conf/php-fpm.conf $finalphpconf
-sudo chown root: $finalphpconf
-finalphpini=/etc/php5/fpm/conf.d/20-$app.ini
-sudo cp ../conf/php-fpm.ini $finalphpini
-sudo chown root: $finalphpini
-sudo service php5-fpm reload
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
 
-# Configure les droits d'accès au fichiers
-# -rw-r--r-- sur les fichiers
-sudo find $final_path -type f | xargs sudo chmod 644
-# drwxr-xr-x sur les dossiers
-sudo find $final_path -type d | xargs sudo chmod 755
-# Les fichiers appartiennent à root
-sudo chown -R root: $final_path
+ADD_SYS_USER	# Créer un utilisateur système dédié à l'app
 
-# www-data doit avoir les droits d'écriture dans plugins, cache et updates
-sudo mkdir -p $final_path/cache
-sudo chown -R www-data $final_path/cache $final_path/plugins $final_path/updates
+#=================================================
+# PHP-FPM CONFIGURATION
+#=================================================
 
+POOL_FPM	# Créer le fichier de configuration du pool php-fpm et le configure.
 
-# Récupération du code de synchronisation
-db_user=$app
-code_sync=$(mysql -h localhost -u $db_user -p$db_pwd -s $db_user -e 'SELECT value FROM leed_configuration WHERE `key`="synchronisationCode"' | sed -n 1p)
+#=================================================
+# SPECIFIC UPGRADE
+#=================================================
+# RETRIEVE SYNCHRONISATION CODE
+#=================================================
 
-# Mise en place du cron pour la synchronisation
+code_sync=$(mysql -h localhost -u $db_name -p$db_pwd -s $db_name -e 'SELECT value FROM leed_configuration WHERE `key`="synchronisationCode"' | sed -n 1p)
+
+#=================================================
+# SETUP CRON FILE FOR SYNCHRONISATION
+#=================================================
+
 sed -i "s@__ADMIN__@$admin@g" ../conf/cron_leed
 sed -i "s@__DOMAIN__@$domain@g" ../conf/cron_leed
-sed -i "s@__PATH__@$path@g" ../conf/cron_leed
+sed -i "s@__PATH__@$path_url@g" ../conf/cron_leed
 sed -i "s@__CODESYNC__@$code_sync@g" ../conf/cron_leed
 sudo cp ../conf/cron_leed /etc/cron.d/$app
+
+#=================================================
+# SECURING FILES AND DIRECTORIES
+#=================================================
+
+# Les fichiers appartiennent à root
+sudo chown -R root: $final_path
+# www-data doit avoir les droits d'écriture dans plugins, cache et updates
+sudo mkdir -p $final_path/cache
+sudo chown -R $app $final_path/cache $final_path/plugins $final_path/updates
+
+#=================================================
+# UPGRADE WITH CURL
+#=================================================
 
 # Vide le cache de leed pour la mise à jour
 sudo rm -rf $final_path/cache/*
@@ -77,11 +145,17 @@ ynh_app_setting_set $app unprotected_uris "/"
 # Régénère la configuration de SSOwat
 sudo yunohost app ssowatconf
 # Lance la procédure de mise à jour de leed.
-curl -kL https://$domain$path
+# curl -kL --resolve $domain:443:127.0.0.1 https://$domain$path_url
+curl -kL -H "Host: $domain" --resolve $domain:443:127.0.0.1 "https://localhost$path_url"
+
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# SETUP SSOWAT
+#=================================================
 
 # Make app private if necessary
-ynh_app_setting_set $app is_public "$is_public"
-if [ "$is_public" = "No" ];
+if [ $is_public -eq 0 ];
 then
 	# Retire l'autorisation d'accès à leed
 	ynh_app_setting_delete $app unprotected_uris
@@ -89,7 +163,8 @@ then
 	ynh_app_setting_set $app skipped_uris "/action.php"
 fi
 
-# Recharge la configuration Nginx
+#=================================================
+# RELOAD NGINX
+#=================================================
+
 sudo service nginx reload
-# Régénère la configuration de SSOwat
-sudo yunohost app ssowatconf
